### ISSUE TITLE
Custom Dot Icons

### ISSUE THREAD

**Issue by gawainb** [glutengo/angular-mgl-timeline#31]
Is there a way to add custom icons either within the dots or in-place of the dots?

**Comment by glutengo** [comment]
Hi, theoretically, this is possible today. You can put any content inside the ```<mgl-timeline-entry-dot>``` component, an icon would be an example. However it would be nice (probably required) to hide the contents of the dot when the entry is expanded because they would move into the header for now. This could be achieved by adding some css which hides the contents via a selector à la ```mgl-timeline-entry.expanded mgl-timeline-entry-dot CONTENT_SELECTOR``` but it would somewhat destroy the apart-from-that-smooth animation.

To achieve this in a nice animation, a change in the library would be needed.
